---
title: "Visualisation des séismes et tsunamis dans le monde de 1965 à 2016"
author: "Niels André, Floriane Cornué & Marion Corbera"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    orientation: columns
    vertical_layout: fill
    navbar:
      - { icon: "fa-github", href: "https://github.com/AgrocampusDS/visualisation-earthsquake", align: right }
params:
  setup_path: ../resources/
---

<style>                     
.navbar {
  background-color:#46ACC8;
  border-color:#46ACC8;
}
.navbar-brand {
color:black!important;
}


</style>   


```{r setup, include=FALSE}
require(flexdashboard)
require(dplyr)
require(stringr)
require(leaflet)
require(ggplot2)
require(magick)
```


```{r}
# Seismes
data <- read.table('earthquake.csv', sep = ',', dec = '.', header = TRUE)
data$Date <- substr(x= data$Date, start = 7, stop = 10)
data <- data %>%
  mutate(dangerosite= case_when(Magnitude <= 6 ~ 'Grand séisme ≤ 6',
                                Magnitude <= 6.9 ~ 'Très grand séisme ≤ 6,9',
                                Magnitude <= 7.9 ~ 'Séisme majeur ≤ 7,9',
                                Magnitude <= 8.9 ~ 'Séisme énorme ≤ 8,9',
                                Magnitude > 8.9 ~ 'Séisme énorme et rare > 8.9')) %>%
  mutate(dangerosite = factor(dangerosite,
                              levels = c('Grand séisme ≤ 6', 'Très grand séisme ≤ 6,9',
                                         'Séisme majeur ≤ 7,9', 'Séisme énorme ≤ 8,9', 'Séisme énorme et rare > 8.9'))) 
data$Type <- as.factor(data$Type)
data$Magnitude.Type <- as.factor(data$Magnitude.Type)
data <- data %>% filter(Magnitude.Type != '')
data <- data %>% filter(Type == 'Earthquake') # Nous ne voulons visualiser que les tremblements de terre
data_clean <- data[-c(7383,20468, 3360),c(1,3,4,5,6,9,22)]
data_clean <- data_clean[order(data_clean$Magnitude),]
div_conv <- read.csv("div_conv.csv", header = TRUE, sep = ";", dec = ",")
# Plaques tectoniques
dbTectonic <- read.csv("tectonic.csv", sep=";")
dbTectonic$lat = as.numeric(dbTectonic$lat)
dbTectonic$lon = as.numeric(dbTectonic$lon)
dbTectonic$plate = as.factor(str_to_upper(dbTectonic$plate))
```

{.tabset}
------------------------------------------------
Carte des plaques tectoniques
=======================================================================

```{r}
map_tectonique = leaflet()%>% addProviderTiles("Esri.WorldImagery")
plates = dbTectonic$plate %>% unique() 
for (plate1 in plates){ #For each plate
  data = dbTectonic[(dbTectonic$plate == plate1),] %>% unique() 
  BorneInf = 0
  for (i in 1:nrow(data)){
    if(i + 1 <= nrow(data)){
      if(abs(data$lon[i]-data$lon[i + 1])>300){
        table1 = data %>% slice((BorneInf + 1):i)
        BorneInf = i
        map_tectonique = map_tectonique %>% 
          addPolylines(data = table1, lat = ~lat,lng =~lon,weight = 3,color = "lightblue")
        
      }
    }
  }
  table1 = data %>%  slice((BorneInf + 1):nrow(data))
  map_tectonique= map_tectonique %>% addPolylines(data = table1, 
                                             lat = ~lat,
                                             lng =~lon,weight = 3,
                                             color = "lightblue")
}
pal2 <- colorFactor(c("green", "purple"), domain = NULL)
map_tectonique <- map_tectonique %>%
  addLabelOnlyMarkers(
    lng = 10, lat = 7.4,
    label = "Plaque Africaine",
    labelOptions = labelOptions(noHide = T, direction = "bottom",
      style = list(
        "color" = "black",
        "font-family" = "arial",
        "font-style" = "italic",
        "font-size" = "3"
      ), opacity = 0.8))%>%
  addLabelOnlyMarkers(
    lng = 46, lat = 22,
    label = "Plaque Arabique",
    labelOptions = labelOptions(noHide = T, direction = "bottom",
      style = list(
        "color" = "black",
        "font-family" = "arial",
        "font-style" = "italic",
        "font-size" = "3"
      ), opacity = 0.8))%>%
  addLabelOnlyMarkers(
    lng = 95, lat = -16,
    label = "Plaque Indo-Australienne",
    labelOptions = labelOptions(noHide = T, direction = "bottom",
      style = list(
        "color" = "black",
        "font-family" = "arial",
        "font-style" = "italic",
        "font-size" = "3"
      ), opacity = 0.8))%>%
  addLabelOnlyMarkers(
    lng = 87, lat = 49,
    label = "Plaque Eurasienne",
    labelOptions = labelOptions(noHide = T, direction = "bottom",
      style = list(
        "color" = "black",
        "font-family" = "arial",
        "font-style" = "italic",
        "font-size" = "3"
      ), opacity = 0.8))%>%
  addLabelOnlyMarkers(
    lng = -49, lat = -15,
    label = "Plaque Sud-Américaine",
    labelOptions = labelOptions(noHide = T, direction = "bottom",
      style = list(
        "color" = "black",
        "font-family" = "arial",
        "font-style" = "italic",
        "font-size" = "3"
      ), opacity = 0.8))%>%
  addLabelOnlyMarkers(
    lng = -90, lat = 33,
    label = "Plaque Nord-Américaine",
    labelOptions = labelOptions(noHide = T, direction = "bottom",
      style = list(
        "color" = "black",
        "font-family" = "arial",
        "font-style" = "italic",
        "font-size" = "3"
      ), opacity = 0.8))%>%
  addLabelOnlyMarkers(
    lng = -104, lat = -18,
    label = "Plaque de Nazca",
    labelOptions = labelOptions(noHide = T, direction = "bottom",
      style = list(
        "color" = "black",
        "font-family" = "arial",
        "font-style" = "italic",
        "font-size" = "3"
      ), opacity = 0.8))%>%
  addLabelOnlyMarkers(
    lng = -146, lat = 13,
    label = "Plaque Pacifique",
    labelOptions = labelOptions(noHide = T, direction = "bottom",
      style = list(
        "color" = "black",
        "font-family" = "arial",
        "font-style" = "italic",
        "font-size" = "3"
      ), opacity = 0.8))%>% 
  addCircleMarkers(data = div_conv, ~long,
                   ~lat,fillColor =  ~pal2(nature),
                   group = ~nature, color = c("green", "purple"),
                   stroke = FALSE, 
                   fillOpacity = 1,
                   radius= 8 )%>%
  addLegend (data = div_conv,labels = c("Divergent", "Convergent"), color = c("green", "purple"), values = ~nature, 
             title = "Mouvement des plaques", 
             position= "bottomright")
map_tectonique
```


Carte des séismes
=======================================================================


```{r}
# Palette de couleur
pal <- colorFactor(c("#fad453","yellow","#e65000","red","#5a213e"), domain = NULL)
# Label des points de séisme
labelSeismes <- paste(
  "Profondeur: ", data_clean$Depth, "<br/>",
  "Magnitude: ", data_clean$Magnitude, "<br/>",
  "Année: ", data_clean$Date, "<br/>") %>%
  lapply(htmltools::HTML)
#pour afficher des données de plusieurs data_sets, il ne faut pas déclarer de data frame dans leaflet(), mais les mettre dans data de chaque objet
map_seismes = leaflet()%>% addProviderTiles("Esri.WorldImagery")
for (plate1 in plates){ #For each plate
  data = dbTectonic[(dbTectonic$plate == plate1),] %>% unique() 
  BorneInf = 0
  for (i in 1:nrow(data)){
    if(i + 1 <= nrow(data)){
      if(abs(data$lon[i]-data$lon[i + 1])>300){
        table1 = data %>% slice((BorneInf + 1):i)
        BorneInf = i
        map_seismes = map_seismes %>% 
          addPolylines(data = table1, lat = ~lat,lng =~lon,weight = 2,color = "black")
        
      }
    }
  }
  table1 = data %>%  slice((BorneInf + 1):nrow(data))
  map_seismes = map_seismes %>% addPolylines(data = table1, 
                                             lat = ~lat,
                                             lng =~lon,weight = 2,
                                             color = "black")
}
map_seismes%>% 
  addCircleMarkers(data = data_clean, ~Longitude,
                   ~Latitude,
                   fillColor = ~pal(dangerosite),
                   group = ~dangerosite,
                   stroke = FALSE, 
                   fillOpacity =~Magnitude/10,
                   radius= ~(exp(Magnitude/4)/2),
                   label = labelSeismes) %>%
  addLegend (data = data_clean, pal = pal, values = ~dangerosite, 
             title = "Dangerosité", 
             position= "bottomright") %>%
  addLayersControl(overlayGroups = c('Grand séisme ≤ 6',
                                     'Très grand séisme ≤ 6,9',
                                     'Séisme majeur ≤ 7,9',
                                     'Séisme énorme ≤ 8,9', 
                                     'Séisme énorme et rare > 8.9'),
                   options = layersControlOptions(collapsed = FALSE)
  )%>%
  addScaleBar(position = "bottomleft")
```

Seismes en fonction de l'année
=======================================================================


### Magnitude moyenne des séismes en fonction de l'année

```{r}
# Séismes
group_year <- data_clean %>% group_by(Date)%>% summarise (n = n(), mean_mag = mean(Magnitude))
group_year$Date <- as.numeric(group_year$Date)
s <-ggplot(data = group_year) +
  geom_bar(aes(x = Date, y=n, fill = mean_mag), stat="identity")+
  ggtitle("Nombre de tremblements de terre par année", subtitle = "entre 1965 et 2016")+
  theme(axis.text.x = element_text(size=10))+
  scale_fill_gradient(low = "yellow", high = "#e65000" )+
  labs(fill = "Magnitude \n Moyenne", x = "Année", y="Nombre de séismes")
s
```